### ISSUE TITLE
403 error from YT for every request

### ISSUE THREAD

**Issue by Miha23833** [lavalink-devs/youtube-source#34] opened 2024-07-13 19:27 UTC
Hello. Last few days I'm getting 403 error when trying to download audio from YT. The error doesn't depend on region my instance is running on. Do you have any ideas why it's broken now? I suggest, it's YT's security updates

**Comment by topi314** [comment] 2024-07-13 19:29
duplicate of https://github.com/lavalink-devs/youtube-source/issues/29

**Closed by topi314** 2024-07-13 19:29 UTC
